### ISSUE TITLE
希望做到既能支持sslv23,又能支持tlsv1,不然ubuntu 12部署正常，16就不行，出现以下错误如下：

### ISSUE THREAD

**Issue by linhcpg** [wallproxy/wallproxy#40]
Traceback (most recent call last):
  File "./startup.py", line 7, in <module>
    from proxy import main
  File "/home/linhcpg/Desktop/wallproxy/local/src.zip/proxy.py", line 3, in <module>
    exec(code.decode('zlib'))
  File "<string>", line 17, in <module>
  File "<string>", line 15, in code
  File "<string>", line 3894, in <module>
  File "<string>", line 10, in main
  File "/usr/local/lib/python2.7/dist-packages/gevent/**init**.py", line 43, in <module>
    from gevent.os import fork
  File "/usr/local/lib/python2.7/dist-packages/gevent/os.py", line 12, in <module>
    from gevent.socket import EAGAIN
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 659, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/usr/local/lib/python2.7/dist-packages/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined

**Comment by linhcpg** [comment]
你的proxy.py是加密，没法自己打开修改呀。。

**Comment by arpit1997** [comment]
>Traceback (most recent call last):
File "./startup.py", line 7, in 
from proxy import main
File "/home/linhcpg/Desktop/wallproxy/local/src.zip/proxy.py", line 3, in 
exec(code.decode('zlib'))
File "", line 17, in 
File "", line 15, in code
File "", line 3894, in 
File "", line 10, in main
File "/usr/local/lib/python2.7/dist-packages/gevent/init.py", line 43, in 
from gevent.os import fork
File "/usr/local/lib/python2.7/dist-packages/gevent/os.py", line 12, in 
from gevent.socket import EAGAIN
File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 659, in 
from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
File "/usr/local/lib/python2.7/dist-packages/gevent/ssl.py", line 386, in 
def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined

Seems to be a ssl problem to me
You can try installing ca-certificates to your machine
